title: Isaacの呟き
name: Isaacの呟き
email: leo@i544c.me
description: WebエンジニアモドキのIsaacのブログ、オタクな話を綴ります
meta_description: WebエンジニアモドキのIsaacのブログ、オタクな話を綴ります
baseurl: ""
url: "https://blog.i544c.me"
domain_name: "https://blog.i544c.me"

# Build settings
remote_theme: rosario/kasper
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
