title: default.cf/blog
name: default.cf/blog
email: nil
description: ヲタクな話を書きます。
meta_description: ヲタクな話を書きます。
baseurl: ""
url: "https://default.cf/blog/"
domain_name: "https://default.cf"
baseurl: "/blog"
permalink: /:year/:month/:day/:title/

# Build settings
remote_theme: rosario/kasper
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

twitter:
  username: defaultcf
  card: summary

social:
  name: defaultcf
  links:
    - https://keybase.io/defaultcf
    - https://github.com/defaultcf
    - https://twitter.com/defaultcf

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
